# Generated by Django 4.0.3 on 2022-05-30 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_clinic',
            fields=[
                ('clinic_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_clinic',
            },
        ),
        migrations.CreateModel(
            name='tbl_help_request',
            fields=[
                ('request_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('request_dt', models.DateField()),
                ('request', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_clinic')),
            ],
            options={
                'db_table': 'tbl_help_request',
            },
        ),
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('vid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('rid', models.IntegerField()),
                ('aid', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_idgen',
            },
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='tbl_patient_reg',
            fields=[
                ('patient_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_clinic')),
            ],
            options={
                'db_table': 'tbl_patient_reg',
            },
        ),
        migrations.CreateModel(
            name='tbl_volunteer',
            fields=[
                ('volunteer_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_clinic')),
            ],
            options={
                'db_table': 'tbl_volunteer',
            },
        ),
        migrations.CreateModel(
            name='tbl_zone',
            fields=[
                ('zone_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=50)),
                ('authority_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_zone',
            },
        ),
        migrations.CreateModel(
            name='tbl_volunteer_allot1',
            fields=[
                ('allot_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('allot_dt', models.DateField()),
                ('comment', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('updates', models.CharField(max_length=50)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_clinic')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_patient_reg')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_help_request')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_volunteer')),
            ],
            options={
                'db_table': 'tbl_volunteer_allot1',
            },
        ),
        migrations.CreateModel(
            name='tbl_volunteer_allot',
            fields=[
                ('allot_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('allot_dt', models.DateField()),
                ('comment', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('updates', models.CharField(max_length=50)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_patient_reg')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_help_request')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_volunteer')),
            ],
            options={
                'db_table': 'tbl_volunteer_allot',
            },
        ),
        migrations.AddField(
            model_name='tbl_volunteer',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_zone'),
        ),
        migrations.AddField(
            model_name='tbl_patient_reg',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_zone'),
        ),
        migrations.AddField(
            model_name='tbl_help_request',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_patient_reg'),
        ),
        migrations.AddField(
            model_name='tbl_help_request',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_zone'),
        ),
        migrations.AddField(
            model_name='tbl_clinic',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_zone'),
        ),
    ]
