# Generated by Django 4.0.3 on 2022-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_tbl_clinic_phone_alter_tbl_patient_reg_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donation',
            fields=[
                ('Donationid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Donationname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=25)),
                ('Phonenumber', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=250)),
                ('Donationtype', models.CharField(max_length=50)),
                ('Donationdetails', models.CharField(max_length=50)),
                ('Donationdate', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_donation',
            },
        ),
        migrations.AddField(
            model_name='tbl_idgen',
            name='donid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
