# Generated by Django 4.0.3 on 2022-06-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_tbl_donation_tbl_idgen_donid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='comid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('Complaintid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Complaintdate', models.DateField()),
                ('Complaint', models.CharField(max_length=250)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_patient_reg')),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
    ]
