# Generated by Django 4.0.3 on 2022-06-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_tbl_idgen_comid_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='revid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('Reviewid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Reviewdate', models.DateField()),
                ('Review', models.CharField(max_length=250)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_patient_reg')),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
    ]
