# Generated by Django 4.0.3 on 2022-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_tbl_idgen_revid_tbl_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_volunteer_allot',
            name='allot_dt',
            field=models.CharField(max_length=50),
        ),
    ]
