# Generated by Django 4.0.3 on 2022-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_tbl_volunteer_allot_allot_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_volunteer_allot',
            name='allot_dt',
            field=models.DateField(),
        ),
    ]
