# Generated by Django 4.0.3 on 2022-06-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_tbl_idgen_upid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_update',
            fields=[
                ('Updateid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Requirement', models.CharField(max_length=250)),
                ('Updatestatus', models.CharField(max_length=250)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_patient_reg')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tbl_help_request')),
            ],
            options={
                'db_table': 'tbl_update',
            },
        ),
    ]
