# Generated by Django 4.0.4 on 2022-07-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_tbl_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_donation',
            old_name='Donationtype',
            new_name='itemname',
        ),
    ]
