# Generated by Django 4.0.4 on 2022-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_tbl_donation_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_help_request',
            name='request_type',
            field=models.CharField(default='ll', max_length=250),
            preserve_default=False,
        ),
    ]
