# Generated by Django 4.0.4 on 2022-07-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_tbl_help_request_request_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_donation',
            old_name='Donationdetails',
            new_name='Item_description',
        ),
    ]
