# Generated by Django 4.0.4 on 2022-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_donationdetails_tbl_donation_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_donation',
            name='Item_name',
            field=models.CharField(default='11', max_length=50),
            preserve_default=False,
        ),
    ]
