# Generated by Django 4.0.4 on 2022-07-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_tbl_donation_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_donation',
            old_name='Item_name',
            new_name='Itemname',
        ),
    ]
