# Generated by Django 4.0.4 on 2022-07-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_rename_item_name_tbl_donation_itemname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_donation',
            old_name='Item_description',
            new_name='Itemdescription',
        ),
    ]
